# Generated by Django 2.0 on 2019-01-04 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_readdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='read_detail_num', to='blog.Blog'),
        ),
    ]
